name : Deploy react application in BeanStalk
on :
    push:
        branches:
            - main
jobs:
    deploy: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout source code
          uses: actions/checkout@v1

        - name: Generate deployment package
          run: zip -r deploy.zip . -x '*.git*'

        - name: Deploy to EB
          uses: einaregilsson/beanstalk-deploy@v21
          with:
            aws_access_key: ${{ secrets.ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
            application_name: ReactApp
            environment_name: ReactApp-env
            version_label: ${{ github.sha }}
            existing_bucket_name: elasticbeanstalk-us-east-1-731599086885
            region: us-east-1
            deployment_package: deploy.zip
            use_existing_version_if_available: "true"
